# Generated by Django 3.0.4 on 2020-03-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='general_innum',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
